packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.22.1
    '@types/node': ^26.6.2
    '@vitest/coverage-v8': ^5.0.1
    '@vitest/ui': ^5.0.1
    eslint: ^10.11.0
    glob: ^13.0.6
    prettier: ^3.9.8
    tsdown: ^0.23.0
    typescript: ^6.0.3
    unrun: ^0.3.1
    vite: ^7.3.6
    vitest: ^5.0.1
    jsdom: ^29.1.1

overrides:
  '@types/node': catalog:dev
